# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(300, 350)
        MainWindow.setMinimumSize(QtCore.QSize(300, 350))
        MainWindow.setMaximumSize(QtCore.QSize(300, 350))
        font = QtGui.QFont()
        font.setPointSize(9)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.mainLabel.setGeometry(QtCore.QRect(0, 0, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.mainLabel.setFont(font)
        self.mainLabel.setObjectName("mainLabel")
        self.outputLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.outputLabel.setGeometry(QtCore.QRect(10, 200, 261, 101))
        self.outputLabel.setText("")
        self.outputLabel.setObjectName("outputLabel")
        self.voteButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.voteButton.setGeometry(QtCore.QRect(10, 70, 93, 28))
        self.voteButton.setObjectName("voteButton")
        self.exitButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(10, 130, 93, 28))
        self.exitButton.setObjectName("exitButton")
        self.voteButton1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.voteButton1.setGeometry(QtCore.QRect(10, 70, 111, 28))
        self.voteButton1.setObjectName("voteButton1")
        self.voteButton2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.voteButton2.setGeometry(QtCore.QRect(10, 110, 111, 28))
        self.voteButton2.setObjectName("voteButton2")
        self.voteButton3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.voteButton3.setGeometry(QtCore.QRect(10, 150, 111, 28))
        self.voteButton3.setObjectName("voteButton3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Project Part 1 "))
        self.mainLabel.setText(_translate("MainWindow", "---------------\n"
"VOTE MENU\n"
"---------------"))
        self.voteButton.setText(_translate("MainWindow", "Vote"))
        self.exitButton.setText(_translate("MainWindow", "Exit"))
        self.voteButton1.setText(_translate("MainWindow", "Vote Cameron"))
        self.voteButton2.setText(_translate("MainWindow", "Vote Allison"))
        self.voteButton3.setText(_translate("MainWindow", "Vote Diego"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
